#include "common/config.h"

#include <sys/stat.h>

#include <cerrno>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <string>

namespace spl {

std::string config_dir() {
    if (const char* d = std::getenv("SPL_CONFIG_DIR")) return d;
    if (const char* x = std::getenv("XDG_CONFIG_HOME")) return std::string(x) + "/spl";
    if (const char* h = std::getenv("HOME")) return std::string(h) + "/.config/spl";
    return "./.spl";
}

std::string config_path() { return config_dir() + "/config"; }

namespace {
std::string trim(const std::string& s) {
    const char* ws = " \t\r\n";
    size_t a = s.find_first_not_of(ws);
    if (a == std::string::npos) return "";
    size_t b = s.find_last_not_of(ws);
    return s.substr(a, b - a + 1);
}

bool mkdirs(const std::string& path) {
    for (size_t i = 1; i <= path.size(); ++i) {
        if (i == path.size() || path[i] == '/') {
            std::string cur = path.substr(0, i);
            if (cur.empty() || cur == ".") continue;
            if (::mkdir(cur.c_str(), 0700) != 0 && errno != EEXIST) return false;
        }
    }
    return true;
}

// Render a rate as a plain integer when whole, avoiding ostream scientific notation.
std::string num(double v) {
    if (v == static_cast<long long>(v)) return std::to_string(static_cast<long long>(v));
    char buf[32];
    std::snprintf(buf, sizeof(buf), "%.3f", v);
    return buf;
}
}  // namespace

Config load_config() {
    Config c;
    std::ifstream f(config_path());
    if (!f) return c;

    std::string line, section;
    while (std::getline(f, line)) {
        std::string t = trim(line);
        if (t.empty() || t[0] == '#' || t[0] == ';') continue;
        if (t[0] == '[') {
            auto end = t.find(']');
            if (end != std::string::npos) section = trim(t.substr(1, end - 1));
            continue;
        }
        auto eq = t.find('=');
        if (eq == std::string::npos) continue;
        std::string key = trim(t.substr(0, eq));
        std::string val = trim(t.substr(eq + 1));

        if (section == "server") {
            if (key == "addr")
                c.server.addr = val;
            else if (key == "port")
                c.server.port = static_cast<uint16_t>(std::atoi(val.c_str()));
            else if (key == "per_ip_rate")
                c.server.per_ip_rate = std::atof(val.c_str());
            else if (key == "per_ip_burst")
                c.server.per_ip_burst = std::atof(val.c_str());
            else if (key == "global_rate")
                c.server.global_rate = std::atof(val.c_str());
            else if (key == "global_burst")
                c.server.global_burst = std::atof(val.c_str());
            else if (key == "cert")
                c.server.cert = val;
            else if (key == "key")
                c.server.key = val;
        } else if (section == "peer") {
            if (key == "addr")
                c.peer.addr = val;
            else if (key == "port")
                c.peer.port = static_cast<uint16_t>(std::atoi(val.c_str()));
        }
    }
    return c;
}

bool config_exists() {
    std::ifstream f(config_path());
    return f.good();
}

bool write_server_config(const ServerConfig& s, std::string* err) {
    if (!mkdirs(config_dir())) {
        if (err) *err = "cannot create " + config_dir();
        return false;
    }
    std::ofstream f(config_path(), std::ios::trunc);
    if (!f) {
        if (err) *err = "cannot write " + config_path();
        return false;
    }
    f << "# splice server configuration (generated by `spl server` setup).\n"
      << "# Edit and re-run, or run `spl server --setup` to reconfigure interactively.\n\n";
    f << "[server]\n";
    f << "addr = " << s.addr << "\n";
    f << "port = " << s.port << "\n";
    f << "per_ip_rate = " << num(s.per_ip_rate) << "\n";
    f << "per_ip_burst = " << num(s.per_ip_burst) << "\n";
    f << "global_rate = " << num(s.global_rate) << "\n";
    f << "global_burst = " << num(s.global_burst) << "\n";
    if (!s.cert.empty()) f << "cert = " << s.cert << "\n";
    if (!s.key.empty()) f << "key = " << s.key << "\n";
    f << "\n# To use THIS server from a client, add to that client's spl config\n"
      << "# (its own " << config_path() << "):\n"
      << "#   [peer]\n"
      << "#   addr = <this server's hostname or public IP>\n"
      << "#   port = " << s.port << "\n";
    f.close();
    ::chmod(config_path().c_str(), 0600);
    return true;
}

}  // namespace spl
